src/main/java/com/ly/oss/entity/GoodsOrder.java
package com.ly.oss.entity;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.ly.oss.comm.OrderStatus;

public class GoodsOrder {

	public GoodsOrder() {
	}
	
	private Long id; //
	private Date createDate; //创建时间
	private Date updateDate; //最后更新时间
	private String updateSid; //最后更新人sid
	private String createSid; //创建人的场景值sid
	private Integer deleted; //是否删除（0：删，1：用）
	private Long weixinPublicId; //微信公众号id
	private Integer orderStatus; //订单状态(1.代付款，2.待发货，3.待收货，4.待评价)
	private Double money; //
	private Double realMoney; //
	private Integer canceled; //是否取消订单
	private String orderCode; //
	private String openid; //
    
    /**
     *
     **/
	public Long getId(){
		return id;
	}
	
	/**
	 *
	 **/
	public void setId(Long id){
		this.id=id;
	}
    /**
     *创建时间
     **/
	public Date getCreateDate(){
		return createDate;
	}
	
	/**
	 *创建时间
	 **/
	public void setCreateDate(Date createDate){
		this.createDate=createDate;
	}
    /**
     *最后更新时间
     **/
	public Date getUpdateDate(){
		return updateDate;
	}
	
	/**
	 *最后更新时间
	 **/
	public void setUpdateDate(Date updateDate){
		this.updateDate=updateDate;
	}
    /**
     *最后更新人sid
     **/
	public String getUpdateSid(){
		return updateSid;
	}
	
	/**
	 *最后更新人sid
	 **/
	public void setUpdateSid(String updateSid){
		this.updateSid=updateSid;
	}
    /**
     *创建人的场景值sid
     **/
	public String getCreateSid(){
		return createSid;
	}
	
	/**
	 *创建人的场景值sid
	 **/
	public void setCreateSid(String createSid){
		this.createSid=createSid;
	}
    /**
     *是否删除（0：删，1：用）
     **/
	public Integer getDeleted(){
		return deleted;
	}
	
	/**
	 *是否删除（0：删，1：用）
	 **/
	public void setDeleted(Integer deleted){
		this.deleted=deleted;
	}
    /**
     *微信公众号id
     **/
	public Long getWeixinPublicId(){
		return weixinPublicId;
	}
	
	/**
	 *微信公众号id
	 **/
	public void setWeixinPublicId(Long weixinPublicId){
		this.weixinPublicId=weixinPublicId;
	}
    /**
     *订单状态(1.代付款，2.待发货，3.待收货，4.待评价)
     **/
	public Integer getOrderStatus(){
		return orderStatus;
	}
	
	/**
	 *订单状态(1.代付款，2.待发货，3.待收货，4.待评价)
	 **/
	public void setOrderStatus(Integer orderStatus){
		this.orderStatus=orderStatus;
	}
    /**
     *
     **/
	public Double getMoney(){
		return money;
	}
	
	/**
	 *
	 **/
	public void setMoney(Double money){
		this.money=money;
	}
    /**
     *
     **/
	public Double getRealMoney(){
		return realMoney;
	}
	
	/**
	 *
	 **/
	public void setRealMoney(Double realMoney){
		this.realMoney=realMoney;
	}
    /**
     *是否取消订单
     **/
	public Integer getCanceled(){
		return canceled;
	}
	
	/**
	 *是否取消订单
	 **/
	public void setCanceled(Integer canceled){
		this.canceled=canceled;
	}
    /**
     *
     **/
	public String getOrderCode(){
		return orderCode;
	}
	
	/**
	 *
	 **/
	public void setOrderCode(String orderCode){
		this.orderCode=orderCode;
	}
    /**
     *
     **/
	public String getOpenid(){
		return openid;
	}
	
	/**
	 *
	 **/
	public void setOpenid(String openid){
		this.openid=openid;
	}
   
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	private String nickname; // 微信昵称
	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
	
	
	public String getOrderStatusName(){
		return OrderStatus.getOrderStatusName(orderStatus.toString());
	}
}

src/main/java/com/ly/oss/entity/GoodsOrderDetail.java
package com.ly.oss.entity;

import org.apache.commons.lang3.builder.ToStringBuilder;

public class GoodsOrderDetail {

	public GoodsOrderDetail() {
	}

	private Long id; //
	private Long orderId; //
	private Long goodsId; //
	private Integer goodsNumber = 0; //

	private Double realPrice = 0.0; // 单价
	private String goodsName; //
	private String goodsDesc; //

	public Double getRealPrice() {
		return realPrice;
	}

	public void setRealPrice(Double realPrice) {
		this.realPrice = realPrice;
	}

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getGoodsDesc() {
		return goodsDesc;
	}

	public void setGoodsDesc(String goodsDesc) {
		this.goodsDesc = goodsDesc;
	}

	/**
	 * 小计
	 * 
	 * @return
	 */
	public Double getTotal() {
		if (goodsNumber == null) {
			return 0.0;
		}

		return goodsNumber * realPrice;
	}

	/**
     *
     **/
	public Long getId() {
		return id;
	}

	/**
	 *
	 **/
	public void setId(Long id) {
		this.id = id;
	}

	/**
     *
     **/
	public Long getOrderId() {
		return orderId;
	}

	/**
	 *
	 **/
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
     *
     **/
	public Long getGoodsId() {
		return goodsId;
	}

	/**
	 *
	 **/
	public void setGoodsId(Long goodsId) {
		this.goodsId = goodsId;
	}

	/**
     *
     **/
	public Integer getGoodsNumber() {
		return goodsNumber;
	}

	/**
	 *
	 **/
	public void setGoodsNumber(Integer goodsNumber) {
		this.goodsNumber = goodsNumber;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}

src/main/java/com/ly/oss/web/goods/OrderController.java
/*******************************************************************************
 * Copyright (c) 2005, 2014 springside.github.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 *******************************************************************************/
package com.ly.oss.web.goods;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ly.oss.entity.GoodsOrder;
import com.ly.oss.entity.GoodsOrderDetail;
import com.ly.oss.service.goods.GoodsOrderDetailService;
import com.ly.oss.service.goods.GoodsOrderService;

/**
 * 管理员管理用户的Controller.
 * 
 * @author Peter
 */
@Controller
@RequestMapping(value = "/order")
public class OrderController {

	@Autowired
	private GoodsOrderService goodsOrderService;
	@Autowired
	private GoodsOrderDetailService goodsOrderDetailService;

	@RequestMapping(method = RequestMethod.GET)
	public String list(Model model) {
		List<GoodsOrder> list = goodsOrderService.getAll();
		model.addAttribute("list", list);
		return "order/orderList";
	}
	
	@RequestMapping(value = "detail/{id}")
	public String detail(@PathVariable("id") Long id, Model model) {
		Long allGoodsNumber = 0L;//共N件（商品数量）
		Double allRealPay = 0.0;//实付
		List<GoodsOrderDetail> detailList = goodsOrderDetailService.getByGoodsOrderId(id);
		for(GoodsOrderDetail goods : detailList){
			allGoodsNumber += goods.getGoodsNumber();
			allRealPay += goods.getTotal();
		}
		
		
		model.addAttribute("goodsOrder", goodsOrderService.getById(id));
		model.addAttribute("detailList", detailList);
		model.addAttribute("allGoodsNumber", allGoodsNumber);
		model.addAttribute("allRealPay", allRealPay);
		return "order/orderDetail";
	}
	
	
}

src/main/webapp/WEB-INF/views/order/orderDetail.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->

<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->

<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->

<head>

	<meta charset="utf-8" />

	<title>订单管理</title>

</head>

<script type="text/javascript" src="${ctx }/static/js/jquery.js"></script>
<script type="text/javascript">

</script>
   
<!-- END HEAD -->

<!-- BEGIN BODY -->

<body class="page-header-fixed">

	<!-- BEGIN CONTAINER -->

	<div class="page-container row-fluid">

		<!-- BEGIN SIDEBAR -->
			<!-- Import Menu -->        
			<jsp:include page="/WEB-INF/layouts/menu.jsp"></jsp:include>
		<!-- END SIDEBAR -->

		<!-- BEGIN PAGE -->
		<div class="page-content">
			<!-- BEGIN PAGE CONTAINER-->        
			<div class="container-fluid">
				<!-- BEGIN PAGE HEADER-->
				<div class="row-fluid">
					<div class="span12">
						<!-- BEGIN STYLE CUSTOMIZER -->
						<!-- Import Style Setting Button -->        
						<jsp:include page="/WEB-INF/layouts/style-setting.jsp"></jsp:include>
						<!-- END BEGIN STYLE CUSTOMIZER -->  

						<!-- BEGIN PAGE TITLE & BREADCRUMB-->
						<h3 class="page-title">订单管理</h3>
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="${ctx}">首页</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li>
								<a href="${ctx}/order">订单管理</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li>订单详情</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
					</div>
				</div>
				<!-- END PAGE HEADER-->

				<!-- BEGIN PAGE CONTENT-->

				<div class="row-fluid">
					<div class="">
						<!-- BEGIN BORDERED TABLE PORTLET-->
						<div class="portlet box red">
							<div class="portlet-title">
								<div class="caption"><i class="icon-euro"></i>订单详情 -- 订单编号【${goodsOrder.orderCode}】<input id="cancel_btn" class="btn" type="button" value="返回" onclick="history.back()"/></div>
								<div class="tools">
									
									<a href="javascript:;" class="collapse"></a>
								</div>
							</div>
							
							<div class="portlet-body">
								<table class="table sliders table-striped">
									<tbody>
										<tr>
											<td style="width:50%">订单编号:<span class="badge badge-inverse">${goodsOrder.orderCode}</span></td>
											<td>
												订单状态:<span class="badge badge-inverse">${goodsOrder.orderStatusName}</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table class="table sliders table-striped table-hover">
									<thead>
										<tr>
											<th>#</th>
											<th style="width:15%">商品名称</th>
											<th>商品描述</th>
											<th>单价</th>
											<th>商品数量</th>
											<th>小计</th>
										</tr>
									</thead>
									<tbody>
										<c:forEach items="${detailList }" var="detail" varStatus="status">
										<tr>
											<td>${status.count}</td>
											<td>${detail.goodsName}</td>
											<td>${detail.goodsDesc}</td>
											<td>${detail.realPrice}</td>
											<td>${detail.goodsNumber}</td>
											<td>${detail.total}</td>
										</tr>
										</c:forEach>
										
										<tr>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td>共<span class="badge badge-info">${allGoodsNumber}</span>件</td>
											<td>实付:<span class="label label-warning">${allRealPay} (元)</span></td>
										</tr>
									</tbody>
								</table>

							</div>
						</div>
						<!-- END BORDERED TABLE PORTLET-->
					</div>

				</div>

				<!-- END PAGE CONTENT-->

			</div>

			<!-- END PAGE CONTAINER-->

		</div>

		<!-- END PAGE -->

	</div>
</body>
	
</html>

src/main/webapp/WEB-INF/views/order/orderList.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->

<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->

<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->

<head>

	<meta charset="utf-8" />

	<title>订单管理</title>

</head>

<script type="text/javascript" src="${ctx }/static/js/jquery.js"></script>
<script type="text/javascript">

</script>
   
<!-- END HEAD -->

<!-- BEGIN BODY -->

<body class="page-header-fixed">

	<!-- BEGIN CONTAINER -->

	<div class="page-container row-fluid">

		<!-- BEGIN SIDEBAR -->

			<!-- Import Menu -->        
			<jsp:include page="/WEB-INF/layouts/menu.jsp"></jsp:include>

		<!-- END SIDEBAR -->

		<!-- BEGIN PAGE -->

		<div class="page-content">

			<!-- BEGIN PAGE CONTAINER-->        

			<div class="container-fluid">

				<!-- BEGIN PAGE HEADER-->

				<%-- <c:if test="${not empty message}">
					<div id="message" class="alert alert-success"><button data-dismiss="alert" class="close"></button>${message}</div>
				</c:if> --%>
				<div class="row-fluid">

					<div class="span12">

						<!-- BEGIN STYLE CUSTOMIZER -->
						<!-- Import Style Setting Button -->        
						<jsp:include page="/WEB-INF/layouts/style-setting.jsp"></jsp:include>
						<!-- END BEGIN STYLE CUSTOMIZER -->  

						<!-- BEGIN PAGE TITLE & BREADCRUMB-->
						<h3 class="page-title">订单管理</h3>
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="${ctx}">首页</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li>订单管理</li>
						</ul>
						<!-- END PAGE TITLE & BREADCRUMB-->
					</div>
				</div>

				<!-- END PAGE HEADER-->

				<!-- BEGIN PAGE CONTENT-->

				<div class="row-fluid">
					<div class="">
						<!-- BEGIN BORDERED TABLE PORTLET-->
						<div class="portlet box red">
							<div class="portlet-title">
								<div class="caption"><i class="icon-euro"></i>订单管理</div>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
								</div>
							</div>
							
							<div class="portlet-body">
								<table class="table table-striped table-bordered  table-hover">
									<thead>
										<tr>
											<th>序号</th>
											<th>订单编号</th>
											<th>微信公众号id</th>
											<th>订单价格</th>
											<th>实付价格</th>
											<th>订单状态</th>
											<th>订货人</th>
											<th>是否取消订单</th>
											<th>创建时间</th>
											<th>最后更新时间</th>
											<th>操作</th>
										</tr>
									</thead>
									<tbody>
										<c:if test="${not empty list}">
											<c:forEach items="${list }" var="single" varStatus="status">
												<tr>
													<td>${status.count}</td>
													<td><a href="${ctx}/order/detail/${single.id}">${single.orderCode}</a></td>
													<td>${single.weixinPublicId }</td>
													<td>${single.money }</td>
													<td>${single.realMoney }</td>
													<td>${single.orderStatusName }</td>
													<td>${single.nickname }</td>
													<td>${single.canceled }</td>
													<td><fmt:formatDate value="${single.createDate }" pattern="yyyy-MM-dd HH:mm"/></td>
													<td><fmt:formatDate value="${single.updateDate }" pattern="yyyy-MM-dd HH:mm"/></td>
													<td>
													</td>
												</tr>
											</c:forEach>
										</c:if>
										<c:if test="${empty list}">
											<tr><td colspan="13" style="text-align: center;"><font style="color:red;text-align: center;">暂无订单！</font></td></tr>
										</c:if>
									</tbody>
								</table>
							</div>
						</div>
						<!-- END BORDERED TABLE PORTLET-->
					</div>
				</div>
				<!-- END PAGE CONTENT-->
			</div>
			<!-- END PAGE CONTAINER-->
		</div>
		<!-- END PAGE -->
	</div>
</body>
	
</html>